version: '3.8'

services:
  pyveng-db:
    container_name: pyveng-db
    image: postgres:14
    restart: unless-stopped
    volumes:
      - uni-db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 5s
      timeout: 5s
      retries: 5

  pyveng-api:
    container_name: pyveng-api
    build: .
    restart: unless-stopped
    depends_on:
      pyveng-db:
        condition: service_healthy
    volumes:
      - .:/app/university/
      - ./static:/app/university/static
      - ./media:/app/university/media
      - /var/log/university:/var/log/university
    env_file:
      - .env
    ports:
      - "8000:8000"

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    expose:
      - 6379
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_URL=6379
    command: redis-server --appendonly yes

volumes:
  uni-db:
    name: uni-db
  redis:
    name: redis
  redis-config:
    name: redis-config